In [7]:
import pandas as pd
file_path = 'data/DataCoSupplyChainDataset.csv'
print("Data loading please wait...")
df = pd.read_csv(file_path, encoding='latin-1')
print("\nData loaded successfully! ✅")
print("Total Rows & Columns:", df.shape)
pd.set_option('display.max_columns', None) 
df.head()

Data loading please wait...

Data loaded successfully! ✅
Total Rows & Columns: (180519, 53)

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,Customer Country,Customer Email,Customer Fname,Customer Id,Customer Lname,Customer Password,Customer Segment,Customer State,Customer Street,Customer Zipcode,Department Id,Department Name,Latitude,Longitude,Market,Order City,Order Country,Order Customer Id,order date (DateOrders),Order Id,Order Item Cardprod Id,Order Item Discount,Order Item Discount Rate,Order Item Id,Order Item Product Price,Order Item Profit Ratio,Order Item Quantity,Sales,Order Item Total,Order Profit Per Order,Order Region,Order State,Order Status,Order Zipcode,Product Card Id,Product Category Id,Product Description,Product Image,Product Name,Product Price,Product Status,shipping date (DateOrders),Shipping Mode
0,DEBIT,3,4,91.250000,314.640015,Advance shipping,0,73,Sporting Goods,Caguas,Puerto Rico,XXXXXXXXX,Cally,20755,Holloway,XXXXXXXXX,Consumer,PR,5365 Noble Nectar Island,725.0,2,Fitness,18.251453,-66.037056,Pacific Asia,Bekasi,Indonesia,20755,1/31/2018 22:56,77202,1360,13.110000,0.04,180517,327.75,0.29,1,327.75,314.640015,91.250000,Southeast Asia,Java Occidental,COMPLETE,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,2/3/2018 22:56,Standard Class
1,TRANSFER,5,4,-249.089996,311.359985,Late delivery,1,73,Sporting Goods,Caguas,Puerto Rico,XXXXXXXXX,Irene,19492,Luna,XXXXXXXXX,Consumer,PR,2679 Rustic Loop,725.0,2,Fitness,18.279451,-66.037064,Pacific Asia,Bikaner,India,19492,1/13/2018 12:27,75939,1360,16.389999,0.05,179254,327.75,-0.80,1,327.75,311.359985,-249.089996,South Asia,Rajastán,PENDING,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/18/2018 12:27,Standard Class
2,CASH,4,4,-247.779999,309.720001,Shipping on time,0,73,Sporting Goods,San Jose,EE. UU.,XXXXXXXXX,Gillian,19491,Maldonado,XXXXXXXXX,Consumer,CA,8510 Round Bear Gate,95125.0,2,Fitness,37.292233,-121.881279,Pacific Asia,Bikaner,India,19491,1/13/2018 12:06,75938,1360,18.030001,0.06,179253,327.75,-0.80,1,327.75,309.720001,-247.779999,South Asia,Rajastán,CLOSED,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/17/2018 12:06,Standard Class
3,DEBIT,3,4,22.860001,304.809998,Advance shipping,0,73,Sporting Goods,Los Angeles,EE. UU.,XXXXXXXXX,Tana,19490,Tate,XXXXXXXXX,Home Office,CA,3200 Amber Bend,90027.0,2,Fitness,34.125946,-118.291016,Pacific Asia,Townsville,Australia,19490,1/13/2018 11:45,75937,1360,22.940001,0.07,179252,327.75,0.08,1,327.75,304.809998,22.860001,Oceania,Queensland,COMPLETE,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/16/2018 11:45,Standard Class
4,PAYMENT,2,4,134.210007,298.250000,Advance shipping,0,73,Sporting Goods,Caguas,Puerto Rico,XXXXXXXXX,Orli,19489,Hendricks,XXXXXXXXX,Corporate,PR,8671 Iron Anchor Corners,725.0,2,Fitness,18.253769,-66.037048,Pacific Asia,Townsville,Australia,19489,1/13/2018 11:24,75936,1360,29.500000,0.09,179251,327.75,0.45,1,327.75,298.250000,134.210007,Oceania,Queensland,PENDING_PAYMENT,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/15/2018 11:24,Standard Class

In [8]:
# 1. Jo columns humein analysis aur dashboard ke liye chahiye
columns_needed = [
    'Type', 'Days for shipping (real)', 'Days for shipment (scheduled)', 
    'Late_delivery_risk', 'Category Name', 'Customer City', 'Customer Segment', 
    'Order City', 'Order Country', 'order date (DateOrders)', 
    'shipping date (DateOrders)', 'Order Item Total', 'Order Status', 'Shipping Mode'
]

# 2. Naya dataframe banayein jisme sirf ye columns hon
df_clean = df[columns_needed].copy()

print("Columns filter ho gaye!")
print("Naye Dataset ka size:", df_clean.shape)

Columns filter ho gaye!
Naye Dataset ka size: (180519, 14)

In [10]:
df_clean.columns = [
    col.lower().replace(' ', '_').replace('(', '').replace(')', '')
    for col in df_clean.columns
]
print("Sql Friendly columns selected ")
print(df_clean.columns.tolist())

Sql Friendly columns selected
['type', 'days_for_shipping_real', 'days_for_shipment_scheduled', 'late_delivery_risk', 'category_name', 'customer_city', 'customer_segment', 'order_city', 'order_country', 'order_date_dateorders', 'shipping_date_dateorders', 'order_item_total', 'order_status', 'shipping_mode']

In [13]:
print(df_clean.dtypes)

type                            object
days_for_shipping_real           int64
days_for_shipment_scheduled      int64
late_delivery_risk               int64
category_name                   object
customer_city                   object
customer_segment                object
order_city                      object
order_country                   object
order_date_dateorders           object
shipping_date_dateorders        object
order_item_total               float64
order_status                    object
shipping_mode                   object
dtype: object

In [16]:
df_clean['order_date_dateorders'] = pd.to_datetime(df_clean['order_date_dateorders'])
df_clean['shipping_date_dateorders'] = pd.to_datetime(df_clean['shipping_date_dateorders'])
print("Dates successfully converted to datetime format! 📅")

Dates successfully converted to datetime format! 📅

In [17]:
print(df_clean.dtypes)

type                                   object
days_for_shipping_real                  int64
days_for_shipment_scheduled             int64
late_delivery_risk                      int64
category_name                          object
customer_city                          object
customer_segment                       object
order_city                             object
order_country                          object
order_date_dateorders          datetime64[ns]
shipping_date_dateorders       datetime64[ns]
order_item_total                      float64
order_status                           object
shipping_mode                          object
dtype: object

In [18]:
import numpy as np 
df_clean['delay_in_days'] = df_clean['days_for_shipping_real'] - df_clean['days_for_shipment_scheduled']
df_clean['delivery_status'] = np.where(df_clean['delay_in_days'] > 0, 'Late', 'On-Time')

print("check new column /n:")

check new column /n:

In [20]:
df_clean.head()

,type,days_for_shipping_real,days_for_shipment_scheduled,late_delivery_risk,category_name,customer_city,customer_segment,order_city,order_country,order_date_dateorders,shipping_date_dateorders,order_item_total,order_status,shipping_mode,delay_in_days,delivery_status
0,DEBIT,3,4,0,Sporting Goods,Caguas,Consumer,Bekasi,Indonesia,2018-01-31 22:56:00,2018-02-03 22:56:00,314.640015,COMPLETE,Standard Class,-1,On-Time
1,TRANSFER,5,4,1,Sporting Goods,Caguas,Consumer,Bikaner,India,2018-01-13 12:27:00,2018-01-18 12:27:00,311.359985,PENDING,Standard Class,1,Late
2,CASH,4,4,0,Sporting Goods,San Jose,Consumer,Bikaner,India,2018-01-13 12:06:00,2018-01-17 12:06:00,309.720001,CLOSED,Standard Class,0,On-Time
3,DEBIT,3,4,0,Sporting Goods,Los Angeles,Home Office,Townsville,Australia,2018-01-13 11:45:00,2018-01-16 11:45:00,304.809998,COMPLETE,Standard Class,-1,On-Time
4,PAYMENT,2,4,0,Sporting Goods,Caguas,Corporate,Townsville,Australia,2018-01-13 11:24:00,2018-01-15 11:24:00,298.250000,PENDING_PAYMENT,Standard Class,-2,On-Time

In [21]:
print("Check Missing Values")
df_clean.isnull().sum()

Check Missing Values

type                           0
days_for_shipping_real         0
days_for_shipment_scheduled    0
late_delivery_risk             0
category_name                  0
customer_city                  0
customer_segment               0
order_city                     0
order_country                  0
order_date_dateorders          0
shipping_date_dateorders       0
order_item_total               0
order_status                   0
shipping_mode                  0
delay_in_days                  0
delivery_status                0
dtype: int64

In [31]:
print("Check Duplicates values")
duplicates = df_clean.duplicated().sum()
print(duplicates)

Check Duplicates values
0

In [32]:
df_clean = df_clean.drop_duplicates()

In [33]:
# 3. Cleaned data ko 'Data' folder mein save karna
final_file_path = 'Data/final_cleaned_supply_chain.csv'
df_clean.to_csv(final_file_path, index=False)

print(f"\n✅ Congratulations! Cleaned dataset successfully saved at: {final_file_path}")

✅ Congratulations! Cleaned dataset successfully saved at: Data/final_cleaned_supply_chain.csv

In [34]:
!pip install sqlalchemy psycopg2

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: sqlalchemy in c:\users\hp\appdata\roaming\python\python311\site-packages (2.0.49)
Requirement already satisfied: psycopg2 in c:\users\hp\appdata\roaming\python\python311\site-packages (2.9.12)
Requirement already satisfied: greenlet>=1 in c:\users\hp\appdata\roaming\python\python311\site-packages (from sqlalchemy) (3.5.0)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\program files\orange\lib\site-packages (from sqlalchemy) (4.11.0)

In [43]:
from sqlalchemy import create_engine
engine = create_engine('postgresql://postgres:12345@localhost:5433/Supply_Chain_Project')
try:
    df_clean.to_sql('supply_chain_data', engine, if_exists='replace', index=False)
    print("✅ Data successfully pushed to PostgreSQL! Ab pgAdmin mein check karein.")
except Exception as e:
    print(f"❌ error: {e}")

✅ Data successfully pushed to PostgreSQL! Ab pgAdmin mein check karein.